name = "Pyonpack-Pojav"
author = "riichi67"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eae03b15e90b9e239d555fe98cc261a86091ff744e0dddc866ebcba9a230ffe"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
