name = "Pyonpack"
author = "masuteri"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b258234dc76d27de42ace94593c5c294b0ac5ff11fdb67c25daaf2d7ba40fcfe"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
